### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by alxppp** [masterkrieger/nuxt-strapi-blog#1]
This is awesome!

Thanks a lot for putting this up, I was just looking into how to connect these two.

How would images work with this setup? Are they served from the Strapi backend or can they be copied into the `_nuxt` dir?

**Comment by masterkrieger** [comment]
The images come from the strapi backend. In `pages/index.vue` I map the Strapi apiUrl (localhost:1337) to the "cover" image url.

ex:
post.cover.url = uploads/5b0bfdf20ff24c140e0e0ca5.jpg
`localhost:1337/uploads/5b0bfdf20ff24c140e0e0ca5.jpg`

**Comment by alxppp** [comment]
Does that work with `nuxt generate`?

https://www.npmjs.com/package/webpack-require-http might help for that

**Comment by masterkrieger** [comment]
I'm not sure. I'm still new to nuxt and all it can do/not do.
I'll have to look into https://www.npmjs.com/package/webpack-require-http.
thanks

**Comment by rajesh-h** [comment]
@alxppp Have you completed this? I am also in middle of building Blog using Strapi and Nuxt
